baseURL = 'https://winzum.nl'
languageCode = 'en-us'
title = 'Lennart van Winzum'
theme = "maverick_winzum"

[menu]
  [[menu.main]]
    identifier = "cv"
    name = "CV"
    url = "/cv"
    weight = "-110"
#   [[menu.main]]
#     identifier = "posts"
#     name = "Post"
#     url = "/posts/"
#     weight = -200